orbis_column_map = {
    "Company name Latin alphabet": "orbis_name", 
    "Orbis ID number": "id",
    "Number of employees\nLast avail. yr": "employees",
    "NACE Rev. 2 main section": "nace_code",
    "City\nLatin Alphabet": "city"
}
kununu_column_map = {
    "firm_name": "kununu_name", 
    "uuid": "kununu_id"
}

abbreviation_map = {
    "aktiengesellschaft": "ag",
    "aktiengeselleschaft": "ag",
    "eingetragener kaufmann": "ek",
    "eingetragene kauffrau": "ek",
    "eingetragene kaufmann als einzelunternehmen": "ek",
    "eingetragener kaufmann als einzelunternehmen": "ek",
    "offene handelsgesellschaft": "ohg",
    "offene handelsgeselleschaft": "ohg",
    "partnerschaftsgesellschaft": "partg",
    "partnerschaftsgeselleschaft": "partg",
    "partnerschaft": "partg",
    "kommanditgesellschaft auf aktien": "kgaa",
    "kommanditgeselleschaft auf aktien": "kgaa",
    "gesellschaft mit beschrankter haftung & co kg": "gmbh & co kg",
    "gesellschaft mit beschraenkter haftung & co kg": "gmbh & co kg",
    "gmbh & co kommanditgesellschaft": "gmbh & co kg",
    "gmbh & co kommanditgeselleschaft": "gmbh & co kg",
    "gesellschaft burgerlichen rechts": "gbr",
    "gesellschaft buergerlichen rechts": "gbr",
    "gesellschaft des burgerlichen rechts": "gbr",
    "gesellschaft des buergerlichen rechts": "gbr",
    "gemeinnutzige gesellschaft mit beschrankter haftung": "ggmbh",
    "gemeinnuetzige gesellschaft mit beschraenkter haftung": "ggmbh",
    "gemeinnuetzige gesellschaft mit beschrankter haftung": "ggmbh",
    "europaische aktiengesellschaft": "se",
    "europaeische aktiengesellschaft": "se",
    "eingetragener verein": "ev",
    "verein": "ev",
    "europaische wirtschaftliche interessensvereinigung": "ewiv",
    "europaeische wirtschaftliche interessensvereinigung": "ewiv",
    "unternehmergesellschaft (haftungsbeschrankt)": "ug",
    "unternehmergeselleschaft (haftungsbeschraenkt)": "ug",
    "stille gesellschaft": "stg",
    "kommanditgesellschaft": "kg",
    "kommanditgeselleschaft": "kg",
    "societas europaea": "se",
    "gesellschaft mit beschrankter haftung": "gmbh",
    "gesellschaft mit beschraenkter haftung": "gmbh",
    "mit beschrankter haftung": "mbh",
    "mit beschraenkter haftung": "mbh",
}

abbreviations = [
    'gmbh & co kg',
    'partg',
    'ggmbh',
    'gmbh',
    'ewiv',
    'kgaa',
    '& co',
    'stg',
    'mbh',
    'ohg',
    'gbr',
    'kg',
    'ek',
    'ev',
    'ug',
    'se',
    'ag'
]